version: '3.9'

services:
  postgres:
    image: postgres:16.2
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=online_voting_db
      - POSTGRES_USER=online_voting_user
      - POSTGRES_PASSWORD=online_voting_password